# Generated by Django 5.2 on 2025-04-27 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_tips', to='trips.trip')),
            ],
            options={
                'verbose_name_plural': 'Travel Tips',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CULTURAL', 'Cultural Advice'), ('LOCAL_INFO', 'Local Information'), ('MUST_HAVE', 'Must Have Items'), ('GENERAL', 'General Tips')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('travel_tips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tips.traveltips')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
