# Generated by Django 4.2.20 on 2025-04-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="end_date",
            new_name="date_leaving",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="start_date",
            new_name="date_return",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="description",
        ),
        migrations.AddField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
