# Generated by Django 4.2.20 on 2025-04-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_rename_end_date_trip_date_leaving_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="date_return",
            new_name="date_returning",
        ),
        migrations.AddField(
            model_name="trip",
            name="activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="PackingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("is_packed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_items",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
    ]
